spring:
  datasource:
    url: jdbc:mysql://localhost:3306/academy_2021?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Mulan605.
    name: MySQL Connection
    driver-class-name: com.mysql.cj.jdbc.Driver
    liquibase:
      enabled: false
server:
  port: 8080
jwt:
  secret: bXlzZWNyZXQ=
  validityInMilis: 3600
files:
  url: /Users/Tatjana/Desktop