
spring:
  profiles:
    active: prod
  application:
    name: predavanja-demo
  liquibase:
    enabled: false
    change-log: classpath:liquibase/master.xml

twitter:
  url: https://twitter.com/api/v1/get-all-tweets
  port: 443
  username: twitter-api-user
  password: twitter-api-password

advance:
  url: https://advanceweb.com
  port: 555
  username: dispecer
  password: dispecer

